- hosts: localhost
  connection: local
  gather_facts: true
  become: yes
  tasks:
    - name: Gather local Tags
      ec2_tag:
        region: "{{ ansible_ec2_placement_region }}"
        resource: "{{ ansible_ec2_instance_id }}"
        state: list
      register: ec2_tags

    - name: List tags
      debug:
        msg: "{{ item.key }} => {{ item.value }}"
      with_dict: "{{ ec2_tags.tags }}

    - name: Add Host to Inventory
      add_host:
        name: "{{ ansible_ec2_hostname }}"
        groups: dynamic_host
        tags: