---

- name: "Install Java and GIT"
  yum: name="java" state="present"
  with_items:
    - java
    - git
    - libselinux-python
    - curl

- name: "Add Jenkins repository"
  get_url: url="http://pkg.jenkins-ci.org/redhat/jenkins.repo" dest="/etc/yum.repos.d/jenkins.repo"

- name: "Import Jenkins key"
  rpm_key: 
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
    state: present
    validate_certs: no

- name: "Install Jenkins"
  yum:
    name: jenkins
    state: present

- name: "Start Jenkins"
  service: name="jenkins" state="started"

- name: "Wait for Jenkins to come up"
  uri:
    url: "http://127.0.0.1:8080"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 1

